# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lakshmi/Downloads/lk/MIVisionX-Inference-Tutorial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lakshmi/Downloads/lk/MIVisionX-Inference-Tutorial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lakshmi/Downloads/lk/MIVisionX-Inference-Tutorial/CMakeFiles /home/lakshmi/Downloads/lk/MIVisionX-Inference-Tutorial/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lakshmi/Downloads/lk/MIVisionX-Inference-Tutorial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named caffeModels

# Build rule for target.
caffeModels: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caffeModels
.PHONY : caffeModels

# fast build rule for target.
caffeModels/fast:
	$(MAKE) -f CMakeFiles/caffeModels.dir/build.make CMakeFiles/caffeModels.dir/build
.PHONY : caffeModels/fast

#=============================================================================
# Target rules for targets named classifier

# Build rule for target.
classifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 classifier
.PHONY : classifier

# fast build rule for target.
classifier/fast:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/build
.PHONY : classifier/fast

source/annmodule.o: source/annmodule.cpp.o

.PHONY : source/annmodule.o

# target to build an object file
source/annmodule.cpp.o:
	$(MAKE) -f CMakeFiles/caffeModels.dir/build.make CMakeFiles/caffeModels.dir/source/annmodule.cpp.o
.PHONY : source/annmodule.cpp.o

source/annmodule.i: source/annmodule.cpp.i

.PHONY : source/annmodule.i

# target to preprocess a source file
source/annmodule.cpp.i:
	$(MAKE) -f CMakeFiles/caffeModels.dir/build.make CMakeFiles/caffeModels.dir/source/annmodule.cpp.i
.PHONY : source/annmodule.cpp.i

source/annmodule.s: source/annmodule.cpp.s

.PHONY : source/annmodule.s

# target to generate assembly for a file
source/annmodule.cpp.s:
	$(MAKE) -f CMakeFiles/caffeModels.dir/build.make CMakeFiles/caffeModels.dir/source/annmodule.cpp.s
.PHONY : source/annmodule.cpp.s

source/classification.o: source/classification.cpp.o

.PHONY : source/classification.o

# target to build an object file
source/classification.cpp.o:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/classification.cpp.o
.PHONY : source/classification.cpp.o

source/classification.i: source/classification.cpp.i

.PHONY : source/classification.i

# target to preprocess a source file
source/classification.cpp.i:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/classification.cpp.i
.PHONY : source/classification.cpp.i

source/classification.s: source/classification.cpp.s

.PHONY : source/classification.s

# target to generate assembly for a file
source/classification.cpp.s:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/classification.cpp.s
.PHONY : source/classification.cpp.s

source/classifier.o: source/classifier.cpp.o

.PHONY : source/classifier.o

# target to build an object file
source/classifier.cpp.o:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/classifier.cpp.o
.PHONY : source/classifier.cpp.o

source/classifier.i: source/classifier.cpp.i

.PHONY : source/classifier.i

# target to preprocess a source file
source/classifier.cpp.i:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/classifier.cpp.i
.PHONY : source/classifier.cpp.i

source/classifier.s: source/classifier.cpp.s

.PHONY : source/classifier.s

# target to generate assembly for a file
source/classifier.cpp.s:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/classifier.cpp.s
.PHONY : source/classifier.cpp.s

source/common.o: source/common.cpp.o

.PHONY : source/common.o

# target to build an object file
source/common.cpp.o:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/common.cpp.o
.PHONY : source/common.cpp.o

source/common.i: source/common.cpp.i

.PHONY : source/common.i

# target to preprocess a source file
source/common.cpp.i:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/common.cpp.i
.PHONY : source/common.cpp.i

source/common.s: source/common.cpp.s

.PHONY : source/common.s

# target to generate assembly for a file
source/common.cpp.s:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/common.cpp.s
.PHONY : source/common.cpp.s

source/region.o: source/region.cpp.o

.PHONY : source/region.o

# target to build an object file
source/region.cpp.o:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/region.cpp.o
.PHONY : source/region.cpp.o

source/region.i: source/region.cpp.i

.PHONY : source/region.i

# target to preprocess a source file
source/region.cpp.i:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/region.cpp.i
.PHONY : source/region.cpp.i

source/region.s: source/region.cpp.s

.PHONY : source/region.s

# target to generate assembly for a file
source/region.cpp.s:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/region.cpp.s
.PHONY : source/region.cpp.s

source/visualize.o: source/visualize.cpp.o

.PHONY : source/visualize.o

# target to build an object file
source/visualize.cpp.o:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/visualize.cpp.o
.PHONY : source/visualize.cpp.o

source/visualize.i: source/visualize.cpp.i

.PHONY : source/visualize.i

# target to preprocess a source file
source/visualize.cpp.i:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/visualize.cpp.i
.PHONY : source/visualize.cpp.i

source/visualize.s: source/visualize.cpp.s

.PHONY : source/visualize.s

# target to generate assembly for a file
source/visualize.cpp.s:
	$(MAKE) -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/source/visualize.cpp.s
.PHONY : source/visualize.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... caffeModels"
	@echo "... rebuild_cache"
	@echo "... classifier"
	@echo "... source/annmodule.o"
	@echo "... source/annmodule.i"
	@echo "... source/annmodule.s"
	@echo "... source/classification.o"
	@echo "... source/classification.i"
	@echo "... source/classification.s"
	@echo "... source/classifier.o"
	@echo "... source/classifier.i"
	@echo "... source/classifier.s"
	@echo "... source/common.o"
	@echo "... source/common.i"
	@echo "... source/common.s"
	@echo "... source/region.o"
	@echo "... source/region.i"
	@echo "... source/region.s"
	@echo "... source/visualize.o"
	@echo "... source/visualize.i"
	@echo "... source/visualize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

